### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by webdevelopland** [Bloggify/showdown-highlight#39] opened 2022-09-11 14:09 UTC
> A parameter initializer is only allowed in a function or constructor implementation

d.ts files can't have any value
![image](https://user-images.githubusercontent.com/28440112/189531896-b81824f8-7d20-4d3a-a992-0e3e7b1fa3dd.png)  
https://github.com/Bloggify/showdown-highlight/blob/master/lib/index.d.ts#L4

**Comment by webdevelopland** [comment] 2022-09-11 14:10
Should be:  
```typescript
import type { ShowdownExtension } from "showdown";

declare function showdownHighlight({
  pre: Boolean,
}): ShowdownExtension[];
export = showdownHighlight;
```

**Comment by webdevelopland** [comment] 2022-09-11 14:33
https://github.com/Bloggify/showdown-highlight/pull/40

**Comment by typehorror** [comment] 2022-09-16 02:13
Would love to see that committed, the issue is preventing any TSC from happening :(

**Comment by IonicaBizau** [comment] 2022-09-16 06:52
Thanks for the 🔔, @typehorror! Taking care of it now.

**Closed as completed** 2022-09-16 06:56 UTC
